import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Sms app unitel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo/logo.webp" />
      </Head>
       <div className='text-xl text-blue-500'>haha</div>
    </div>
  )
}
